# Generated by Django 5.2.7 on 2025-11-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_persona_es_admin_persona_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='personas/documentos/'),
        ),
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personas/fotos/'),
        ),
    ]
