# Generated by Django 5.2.7 on 2025-11-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos_mascotas/'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mascotas/'),
        ),
    ]
