# Generated by Django 5.2.7 on 2025-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0002_mascota_documento_mascota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_rescate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
