# Generated by Django 5.2 on 2025-11-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mascotas', '0001_initial'),
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.mascota')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.persona')),
            ],
        ),
    ]
